### ISSUE TITLE
Mapping of UPayloadFormat to MIME types

### ISSUE THREAD

**Issue by sophokles73** [eclipse-uprotocol/uprotocol-core-api#88]
The [UPayload definition](https://github.com/eclipse-uprotocol/uprotocol-core-api/blob/uprotocol-core-api-1.5.3/src/main/proto/upayload.proto) also contains the `UPayloadFormat` which is supposed to indicate the *serialization format* of the payload.

Is this information supposed to be conveyed in a transport protocol specific way, e.g. by means of a MIME type set in a *content-type* header/attribute? If so, what are the MIME types that the formats correspond to?

**Comment by stevenhartley** [comment]
We mapped MIME types in UCloudEvents.java in the Java SDK if you want to see examples but it is important to differentiate the data content type and the message envelope content type that can (and often are) different. 

Today our vehicle-2-cloud transport is MQTT where the message format is CloudEvent. In this scenaro, the data is protobuf encoded message, while the CloudEvent itself is json serialized format (per CloudEvent specifications). We did it this way so that the cloud dispatchers could easily read sink/source attributes for routing. In this example, the MQTT contenttype attribute is set to "application/json" while the CloudEvent attribute  "datacontenttype" (now maps to PayloadFormat) is "application/x-protobuf" (this tells us that we are packing google.protobuf.Any so that the data also has the schema).

Having said that, we probably should document so that there is no ambiguity for MIME type mapping (agreed), should I can put this in the proto (a custom option), make sense?

**Comment by sophokles73** [comment]
> Having said that, we probably should document so that there is no ambiguity for MIME type mapping (agreed), should I can put this in the proto (a custom option), make sense?

FMPOV that would make a lot of sense. We should be able to define unambiguous mappings of UPayloadFormat to MIME types in the upayload.proto file. Using an option would open up the opportunity to automatically generate code for the mapping but simply having a comment would work for now, I guess.

Just to be clear: my understanding would then be that these MIME types are (to be) used by concrete mappings to transport protocols, if and where a MIME type makes sense, e.g. in content-type fields. But as you also stated, care needs to be taken when using CloudEvents for the binding that do not use binary mapping, i.e. wrapping the (real) payload in CloudEvent envelope.

**Comment by stevenhartley** [comment]
@sophokles73 please help to review #89

**Comment by stevenhartley** [comment]
Closing as #89 was merged
